"""
Apply Deformation: Map inference PLY point cloud displacements back to mesh.

Uses nearest-neighbor (KDTree) correspondence between mesh vertices and
inference point cloud to transfer per-frame displacements onto the original
mesh, producing a deformed OBJ sequence that preserves face topology.

Usage:
    python exp_motion/utils/apply_deformation.py \
        --mesh_path data/{dataset}/mesh/mesh_frame_0000.obj \
        --ply_dir  output/inference/{dataset}/.../output/ \
        --output_dir output/animation/{dataset}/
"""

import argparse
import os
from glob import glob

import numpy as np
import open3d as o3d
import trimesh
from scipy.spatial import cKDTree


# ---------------------------------------------------------------------------
# I/O helpers
# ---------------------------------------------------------------------------

def load_ply_points(path):
    """Load a PLY file and return an (N, 3) float64 array of points."""
    pcd = o3d.io.read_point_cloud(path)
    return np.asarray(pcd.points)


def load_mesh(path):
    """Load an OBJ mesh via trimesh, preserving original topology."""
    mesh = trimesh.load(path, process=False, force="mesh")
    return mesh


def save_obj(vertices, faces, output_path):
    """
    Write a minimal OBJ file preserving the original face topology.

    Parameters
    ----------
    vertices : (V, 3) array
    faces : (F, 3) array of 0-based vertex indices
    output_path : str
    """
    with open(output_path, "w") as f:
        f.write("# Deformed mesh generated by apply_deformation.py\n")
        for v in vertices:
            f.write(f"v {v[0]:.8f} {v[1]:.8f} {v[2]:.8f}\n")
        for face in faces:
            # OBJ uses 1-based indices
            v1, v2, v3 = face + 1
            f.write(f"f {v1} {v2} {v3}\n")


# ---------------------------------------------------------------------------
# Core deformation logic
# ---------------------------------------------------------------------------

def build_correspondence(mesh_vertices, ply_points, threshold=None):
    """
    For each mesh vertex, find the nearest point in the PLY point cloud.

    Parameters
    ----------
    mesh_vertices : (V, 3) array
    ply_points : (P, 3) array
    threshold : float or None
        If set, only keep correspondences where distance <= threshold.
        If None, keep all (every mesh vertex gets a match).

    Returns
    -------
    mesh_indices : (M,) int array – indices into mesh_vertices
    ply_indices  : (M,) int array – indices into ply_points
    distances    : (M,) float array – distances for each pair
    """
    tree = cKDTree(ply_points)
    distances, indices = tree.query(mesh_vertices, k=1)

    if threshold is not None:
        mask = distances <= threshold
        mesh_idx = np.where(mask)[0]
        ply_idx = indices[mask]
        dists = distances[mask]
    else:
        mesh_idx = np.arange(len(mesh_vertices))
        ply_idx = indices
        dists = distances

    return mesh_idx, ply_idx, dists


def apply_displacement(original_vertices, ref_ply, cur_ply, mesh_idx, ply_idx):
    """
    Compute displacement from reference PLY to current PLY for each
    correspondence, and apply it to the original mesh vertices.

    new_vertex[i] = original_vertex[i] + (cur_ply[j] - ref_ply[j])

    Parameters
    ----------
    original_vertices : (V, 3) array – frame-0 mesh vertices
    ref_ply : (P, 3) array – frame-0 PLY points
    cur_ply : (P, 3) array – current-frame PLY points
    mesh_idx : (M,) int array
    ply_idx : (M,) int array

    Returns
    -------
    deformed : (V, 3) array – new vertex positions
    """
    deformed = original_vertices.copy()
    displacements = cur_ply[ply_idx] - ref_ply[ply_idx]
    deformed[mesh_idx] += displacements
    return deformed


# ---------------------------------------------------------------------------
# PLY discovery
# ---------------------------------------------------------------------------

def discover_ply_frames(ply_dir):
    """
    Find all gt_*.ply files in ply_dir and return them sorted by frame index.

    Returns list of (frame_index, file_path) tuples.
    """
    pattern = os.path.join(ply_dir, "gt_*.ply")
    files = sorted(glob(pattern))
    frames = []
    for f in files:
        basename = os.path.basename(f)          # gt_0.ply
        name = os.path.splitext(basename)[0]    # gt_0
        idx = int(name.split("_")[1])           # 0
        frames.append((idx, f))
    frames.sort(key=lambda x: x[0])
    return frames


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Apply inference PLY displacements to mesh via nearest-neighbor correspondence."
    )
    parser.add_argument("--mesh_path", required=True,
                        help="Path to the reference mesh OBJ (frame 0)")
    parser.add_argument("--ply_dir", required=True,
                        help="Directory containing gt_*.ply inference output")
    parser.add_argument("--output_dir", required=True,
                        help="Output directory for deformed mesh OBJs")
    parser.add_argument("--threshold", type=float, default=None,
                        help="Max distance for correspondence (None = use all vertices)")
    args = parser.parse_args()

    # Load reference mesh
    print(f"Loading reference mesh: {args.mesh_path}")
    mesh = load_mesh(args.mesh_path)
    original_vertices = np.array(mesh.vertices, dtype=np.float64)
    faces = np.array(mesh.faces)
    print(f"  Vertices: {len(original_vertices)}, Faces: {len(faces)}")

    # Discover PLY frames
    ply_frames = discover_ply_frames(args.ply_dir)
    if not ply_frames:
        print(f"ERROR: No gt_*.ply files found in {args.ply_dir}")
        return

    print(f"Found {len(ply_frames)} PLY frames in {args.ply_dir}")

    # Load reference (frame 0) point cloud
    ref_idx, ref_path = ply_frames[0]
    print(f"Loading reference PLY (frame {ref_idx}): {ref_path}")
    ref_ply = load_ply_points(ref_path)
    print(f"  Points: {len(ref_ply)}")

    # Build correspondence
    print("Building KDTree correspondence...")
    mesh_idx, ply_idx, dists = build_correspondence(
        original_vertices, ref_ply, threshold=args.threshold
    )
    print(f"  Matched {len(mesh_idx)}/{len(original_vertices)} mesh vertices")
    if len(mesh_idx) > 0:
        print(f"  Distance stats: min={dists.min():.6f}, max={dists.max():.6f}, "
              f"mean={dists.mean():.6f}, median={np.median(dists):.6f}")

    if len(mesh_idx) == 0:
        print("ERROR: No correspondences found. Check that mesh and PLY are in the same coordinate space.")
        return

    # Create output directory
    os.makedirs(args.output_dir, exist_ok=True)

    # Process each frame
    print(f"\nDeforming mesh for {len(ply_frames)} frames...")
    for i, (frame_idx, ply_path) in enumerate(ply_frames):
        cur_ply = load_ply_points(ply_path)

        deformed_verts = apply_displacement(
            original_vertices, ref_ply, cur_ply, mesh_idx, ply_idx
        )

        output_path = os.path.join(args.output_dir, f"mesh_frame_{frame_idx:04d}.obj")
        save_obj(deformed_verts, faces, output_path)

        if i % 10 == 0 or i == len(ply_frames) - 1:
            print(f"  Frame {frame_idx} -> {output_path}")

    print(f"\nDone! {len(ply_frames)} deformed meshes saved to {args.output_dir}")


if __name__ == "__main__":
    main()
